name: Update and commit data

on:
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * 0"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Pull LFS
        run: git lfs pull

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      # Get RNS_API_KEY from GH Secrets and save to .env:
      - name: Create .env file
        run: |
          echo "RNS_API_KEY=${{ secrets.RNS_API_KEY }}" >> .env

      - name: Check if db file exists
        run: |
          if [ ! -f playlist.db ]; then
            echo "Database file not found!"
            exit 1
          fi
          # size of the file
          echo "Database file size: $(du -h playlist.db | cut -f1)"

      - name: Generate database
        run: uv run main.py --fetch --save-to-db

      - name: Export statistics
        run: uv run export_stats.py

      - name: Commit changes to website and data folder
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add website data playlist.db
          git commit -m "Update website and data"
          git push

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './website'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4